export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const ORDENAR_VIDEOGAMES = "ORDENAR_VIDEOGAMES";
export const FILTRAR_GENEROS = "FILTRAR_GENEROS";
export const FILTRAR_CREADOS = "FILTRAR_CREADOS";
export const FILTRAR_EXISTENTES = "FILTRAR_EXISTENTES";
